export const LIST_STATES = "LIST_STATES";
export const LIST_DISEASES = "LIST_DISEASES";
export const LIST_COUNTIES = "LIST_COUNTIES";
export const LIST_FAVORITES_COUNTIES = "LIST_FAVORITES_COUNTIES";
export const LIST_COUNTY_STATS = "LIST_COUNTY_STATS";
export const LIST_COUNTY = "LIST_COUNTY";
export const MARK_COUNTY_FAVORITE = "MARK_COUNTY_FAVORITE";
export const MARK_COUNTY_NON_FAVORITE = "MARK_COUNTY_NON_FAVORITE";
